name: Deploy Argo CD to GKE

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_default_credentials: true

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin   

    - name: Configure kubectl
      run: |-
        gcloud container clusters get-credentials hub-sandbox-cluster --zone us-east1-b --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Create Argo CD namespace
      run: kubectl create namespace argocd

    - name: Deploy Argo CD
      run: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.1/manifests/install.yaml

    - name: Expose Argo CD
      run: kubectl patch svc argocd-server -n argocd -p '{"metadata":{"annotations":{"networking.gke.io/load-balancer-type":"Internal"}},"spec":{"type":"LoadBalancer"}}'


